version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '8090:8090'
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - '8000:8000'
