version: '3.9'

services:
  frontend:
    image: eyadhussein/secret-front
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '8090:8090'
    depends_on:
      - backend
  backend:
    image: eyadhussein/secret-back
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - '8000:8000'
